# Generated by Django 5.1.6 on 2026-01-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="Paste full YouTube URL here (e.g. https://www.youtube.com/watch?v=...)",
                null=True,
            ),
        ),
    ]
